language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

script:
- ./gradlew check lint test assemble
